import Head from "next/head";
import Button from "./Button";
import Link from "next/link";

const Header = () => {
    return (
        <header style={{ marginBottom: '50px' }}>
            <Head>
                <title>Фотосток</title>
                <meta name="title" content='фотографии' />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                
            </Head>

            <nav>
                <div className="nav-wrapper">
                    <Link href="/" className="brand-logo">Logo</Link>
                    <ul id="nav-mobile" className="right hide-on-med-and-down">
                        <li>
                            <input placeholder="поиск" type="text"
                                style={{ color: 'white', border: 'none' }}

                            /></li>
                        <li><Link href="/">Главная</Link></li>
                        <li><Link href="badges.html">О проекте</Link></li>
                        <li><Link href="collapsible.html">Контакты</Link></li>
                        <Button text={'войти'} linktext={'auth'} />
                        <Button text={'регистрация'} linktext={'registration'} />
                    </ul>
                </div>
                <div className="nav-wrapper">
                </div>
            </nav>
        </header>
    )
}

export default Header;